---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrydoy6068.azurecr.io/tripinsights/user-java:1.0
        env:
          - name: SQL_SERVER
            valueFrom:
              configMapKeyRef:
                name: sqlserver-configmap
                key: sql_server
          - name: SQL_DBNAME
            valueFrom:
              configMapKeyRef:
                name: sqlserver-configmap
                key: sql_dbname
          - name: SQL_USER
            valueFrom:
              configMapKeyRef:
                name: sqlserver-configmap
                key: sql_user
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlserver
                key: password
        ports:
        - containerPort: 80
