apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 6
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrydoy6068.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
          name: tripviewer
        env:
        - name: TRIPS_API_ENDPOINT
          value: http://trips.api.svc.cluster.local
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile.api.svc.cluster.local
