kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: Group
  namespace: web
  name: e2144027-bbb0-4b70-a1a3-03b355bf156c
