kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: aefbc62c-fe1e-4f4c-af0d-4b7aef966ee3
