kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: API view
  namespace: api
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["view"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: API edit
  namespace: api
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["view"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Web view
  namespace: api
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["view"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Web edit
  namespace: api
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", deletecollection get list patch update watch"]
---
