apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrydoy6068.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
          name: poi
